-- Changement 27 Novembre : Ajout prénom dans table 'suspect'

INSERT INTO `suspect` (`id`, `first_name`, `name`, `gender`, `age`, `physical_description`, `alibi`)
VALUES (1, 'Margaret', 'Thornton', 'F', 45, 'Femme ''apparence distinguée avec des cheveux blonds',
        'Était dans sa chambre toute la soirée, lisant un livre'),
       (2, 'Elizabeth', 'Thornton', 'F', 22, 'Jeune femme aux cheveux bruns et yeux verts',
        'Était au piano dans le salon, pratiquant'),
       (3, 'William', 'Thornton', 'M', 25, 'Homme élégant aux cheveux noirs, yeux bleus',
        'Sorti pour une promenade nocturne, seul'),
       (4, 'Emily', 'Navy', 'F', 35, 'Femme de ménage avec des cheveux bruns attachés en queue de cheval',
        'Nettoyait les couloirs du manoir'),
       (5, 'John', 'Smith', 'M', 40, 'Homme d''affaires avec des lunettes et une barbe',
        'Était dans son bureau, travaillant sur des documents'),
       (6, 'Rebecca', 'Johnson', 'F', 28, 'Secrétaire avec des cheveux roux', 'A fait des courses en ville, seule'),
       (7, 'Charles', 'Davis', 'M', 50, 'Garde de sécurité avec une carrure imposante', 'En patrouille dans le jardin'),
       (8, 'Sophie', 'Anderson', 'F', 32, 'Cuisinière avec une toque blanche', 'Préparait le dîner dans la cuisine'),
       (9, 'Michael', 'Brown', 'M', 35, 'Chauffeur avec une veste noire',
        'Conduisait la voiture familiale pour une sortie nocturne'),
       (10, 'Olivia', 'White', 'F', 25, 'Femme de chambre avec un uniforme propre',
        'Nettoyait les chambres des invités'),
       (11, 'Daniel', 'Miller', 'M', 45, 'Jardinier avec des bottes en caoutchouc',
        'Travaillait dans le jardin toute la soirée'),
       (12, 'Emma', 'Thomas', 'F', 30, 'Infirmière avec une blouse blanche',
        'Était dans la salle de soins, organisant le matériel médical'),
       (13, 'George', 'Davis', 'M', 28, 'Ami de la victime avec des cheveux bruns',
        'Travaillait dans son bureau, traitant des affaires financière'),
       (14, 'Helen', 'Carter', 'F', 38, 'Gouvernante avec des lunettes rondes',
        'Faisait des comptes dans le bureau principal'),
       (15, 'Benjamin', 'Taylor', 'M', 55, 'Tuteur privé avec une chemise et une cravate',
        'Donnait des leçons à Elizabeth dans la bibliothèque'),
       (16, 'Jessica', 'Roberts', 'F', 26, 'Artiste avec des cheveux violets', 'Peignait dans son atelier'),
       (17, 'Andrew', 'Wilson', 'M', 33, 'Technicien informatique avec un ordinateur portable',
        'Réparait l''ordinateur dans le salon'),
       (18, 'Evelyn', 'Moore', 'F', 40, 'Coach de fitness avec une tenue de sport',
        'Faisait de l''exercice dans la salle de sport'),
       (19, 'Peter', 'Thompson', 'M', 48, 'Architecte avec des lunettes et une chemise à carreaux',
        'Travaillait sur des plans dans la salle d''étude'),
       (20, 'Isabella', 'Clark', 'F', 23, 'Mannequin avec des cheveux longs et bruns',
        'Faisait une séance photo dans le jardin'),
       (21, 'George', 'Hall', 'M', 30, 'Électricien avec des outils à la ceinture',
        'Réparait les lumières dans le couloir'),
       (22, 'Charlotte', 'Harris', 'F', 35, 'Psychologue avec des lunettes et une blouse',
        'Conseillait Elizabeth dans son bureau'),
       (23, 'Samuel', 'Reed', 'M', 42, 'Agent immobilier avec un costume',
        'Discutait des affaires immobilières avec Richard dans le salon'),
       (24, 'Natalie', 'King', 'F', 27, 'Écrivaine avec des cheveux blonds',
        'Rédigeait un nouveau chapitre dans la bibliothèque'),
       (25, 'Nicholas', 'Evans', 'M', 31, 'Musicien avec une guitare', 'Jouait de la musique dans le hall'),
       (26, 'Victoria', 'Lopez', 'F', 36, 'Avocate avec un tailleur élégant', 'Révisait des documents dans son bureau'),
       (27, 'Dylan', 'Hughes', 'M', 29, 'Photographe avec un appareil photo autour du cou',
        'Prenait des photos dans le jardin'),
       (28, 'Grace', 'Ward', 'F', 33, 'Consultante en relations publiques avec des talons hauts',
        'Planifiait un événement dans la salle de réception'),
       (29, 'Eric', 'Morgan', 'M', 39, 'Traducteur avec des lunettes',
        'Travaillait sur des traductions dans la bibliothèque'),
       (30, 'Lilliane', 'Foster', 'F', 41, 'Vétérinaire avec une blouse blanche',
        'Soignait les animaux de compagnie dans la salle des animaux'),
       (31, 'Timothy', 'Cook', 'M', 34, 'Chef cuisinier avec une toque et une veste blanche',
        'Supervisait la préparation du dîner dans la cuisine'),
       (32, 'Fiona', 'Bennett', 'F', 29, 'Styliste avec des cheveux roses', 'Créait des tenues dans son atelier'),
       (33, 'Vincent', 'Gray', 'M', 43, 'Astronome avec une lunette télescopique',
        'Observait les étoiles sur la terrasse'),
       (34, 'Mia', 'Hughes', 'F', 24, 'Étudiante avec une mallette', 'Étudiait dans la bibliothèque'),
       (35, 'Robert', 'Turner', 'M', 37, 'Ingénieur avec une trousse à outils',
        'Réparait des équipements dans le sous-sol'),
       (36, 'Emily', 'Watson', 'F', 31, 'Journaliste avec un carnet de notes',
        'Interviewait des membres de la famille pour un article'),
       (37, 'Oscar', 'Brown', 'M', 46, 'Acteur avec un costume élégant', 'Répétait ses lignes dans le salon'),
       (38, 'Sophia', 'Bennett', 'F', 26, 'Couturière avec des épingles dans les cheveux',
        'Cousait des robes dans son atelier'),
       (39, 'Jeffrey', 'Turner', 'M', 44, 'Agent de sécurité avec une oreillette habillé en violet',
        'Surveillait les caméras de sécurité dans la salle de surveillance'),
       (40, 'Isabel', 'Walker', 'F', 39, 'Psychiatre avec une blouse blanche',
        'Parlait avec des membres de la famille dans le bureau principal'),
       (41, 'Jonathan', 'Reed', 'M', 32, 'Pompier avec une veste et un casque',
        'Inspectait les extincteurs dans le couloir'),
       (42, 'Nina', 'Russell', 'F', 27, 'Danseuse avec des chaussons de ballet',
        'Répétait une chorégraphie dans le salon'),
       (43, 'Matthew', 'Turner', 'M', 36, 'Chirurgien avec une blouse verte',
        'Était d''astreinte à l''hôpital pour une urgence'),
       (44, 'Laura', 'Carter', 'F', 34, 'Conseillère financière avec des lunettes',
        'Révisait les comptes dans le bureau principal'),
       (45, 'Patrick', 'Lewis', 'M', 49, 'Chauffeur de limousine avec un uniforme',
        'Attendait à l''extérieur du manoir pour un appel'),
       (46, 'Melanie', 'Reed', 'F', 30, 'Fleuriste avec des mains couvertes de terre',
        'Préparait des arrangements floraux dans le salon'),
       (47, 'Mark', 'Robinson', 'M', 38, 'Agent immobilier avec un sourire charismatique',
        'Discutait de propriétés avec Richard dans le bureau principal'),
       (48, 'Samantha', 'Ward', 'F', 33, 'Conseillère en relations publiques avec un téléphone portable',
        'Organisait la communication de la famille Thornton'),
       (49, 'Keith', 'Allen', 'M', 42, 'Ingénieur informatique avec un badge d''identification',
        'Vérifiait les systèmes informatiques dans le salon'),
       (50, 'Claire', 'Evans', 'F', 29, 'Astronome avec des étoiles dans les yeux',
        'Discutait de l''astronomie avec Vincent sur la terrasse'),
       (51, 'Julia', 'Turner', 'F', 31, 'Avocate avec un air déterminé', 'Préparait des documents dans son bureau'),
       (52, 'Gregory', 'Clark', 'M', 40, 'Psychiatre avec une attitude calme',
        'Consultait des membres de la famille dans le bureau principal'),
       (53, 'Madeline', 'Harris', 'F', 35, 'Styliste avec des échantillons de tissu',
        'Créait des designs dans son atelier'),
       (54, 'Connor', 'Brown', 'M', 27, 'Joueur de poker avec des lunettes de soleil',
        'Participait à une partie de poker dans le salon'),
       (55, 'Amanda', 'White', 'F', 26, 'Secrétaire avec un sourire amical',
        'Répondait aux appels dans le bureau principal'),
       (56, 'Victor', 'Miller', 'M', 48, 'Chef cuisinier avec une toque élégante',
        'Supervisait la préparation du dîner dans la cuisine'),
       (57, 'Nicole', 'Davis', 'F', 29, 'Jardinière avec des gants de jardinage',
        'Entretenait les plantes dans le jardin'),
       (58, 'Leonard', 'Robinson', 'M', 37, 'Pianiste avec des doigts agiles', 'Jouait du piano dans le salon'),
       (59, 'Rachael', 'Anderson', 'F', 34, 'Cuisinière avec une passion pour la pâtisserie',
        'Préparait des desserts dans la cuisine'),
       (60, 'Alan', 'King', 'M', 45, 'Photographe avec un appareil professionnel',
        'Capturait des moments familiaux dans le salon'),
       (61, 'Marissa', 'Lewis', 'F', 32, 'Agent immobilier avec des brochures de propriétés',
        'Discutait d''opportunités immobilières avec Richard dans le bureau principal'),
       (62, 'Ethan', 'Turner', 'M', 29, 'Étudiant en médecine avec une blouse blanche',
        'Étudiait dans la bibliothèque'),
       (63, 'Sandra', 'Bennett', 'F', 41, 'Aide-soignante avec une empathie naturelle',
        'Assistait les membres de la famille dans le besoin'),
       (64, 'Owen', 'Foster', 'M', 33, 'Artiste de rue avec des vêtements colorés',
        'Créait une fresque sur le mur extérieur du manoir'),
       (65, 'Caroline', 'Ward', 'F', 28, 'Éditrice avec un stylo et des manuscrits',
        'Révisait des écrits dans le salon'),
       (66, 'Dominic', 'Hughes', 'M', 34, 'Chanteur avec une voix envoûtante',
        'Interprétait des chansons dans la salle de musique'),
       (67, 'Veronica', 'Reed', 'F', 37, 'Architecte d''intérieur avec un œil pour le design',
        'Était en train de réorganiser le mobilier dans le salon'),
       (68, 'Walter', 'Clark', 'M', 39, 'Technicien en électronique avec des gadgets',
        'Réparait des appareils électroniques dans le salon'),
       (69, 'Jennifer', 'Taylor', 'F', 30, 'Pâtissière avec des mains enfarinées',
        'Créait des gâteaux dans la cuisine'),
       (70, 'Dennis', 'Walker', 'M', 36, 'Électricien avec un testeur de tension',
        'Vérifiait les installations électriques dans le couloir'),
       (71, 'Ava', 'Turner', 'F', 28, 'Journaliste avec un bloc-notes',
        'Interviewait les membres de la famille pour un article'),
       (72, 'Frank', 'Turner', 'M', 42, 'Vétérinaire avec une affection pour les animaux',
        'Soignait les animaux de compagnie dans la salle des animaux'),
       (73, 'Catherine', 'White', 'F', 35, 'Couturière chauve', 'Cousait des robes avec Sophia'),
       (74, 'Victor', 'King', 'M', 37, 'Nutritionniste Sportif et très petit', 'Organisait les repas pour la famille'),
       (75, 'Holly', 'Taylor', 'F', 26, 'Étudiante en arts avec des cheveux roses', 'Peignait dans le salon'),
       (76, 'Harry', 'Davis', 'M', 33, 'Agent de sécurité avec une oreillette petit et vêtu de rouge',
        'Surveillait le 2ème étage'),
       (77, 'Emma', 'Roberts', 'F', 29, 'Cheffe de cuisine en tablier noir et rouge',
        'S''occupait des autres cuisiniers avec Timothy'),
       (78, 'Max', 'Turner', 'M', 40, 'Pompier avec une veste et un casque',
        'Inspectait les extincteurs avec Jonathan'),
       (79, 'Laura', 'Anderson', 'F', 31, 'Professeure de danse avec un tutu rose',
        'Enseignait une chorégraphie au groupe de Nina'),
       (80, 'Chris', 'Harris', 'M', 45, 'Ouvrier avec un casque et un gilet orange', 'Goudronnait le nouveau parking'),
       (81, 'Lily', 'Robinson', 'F', 24, 'Yogini habillé en tenue de sport',
        'Faisait une séance yoga avec William dans le jardin'),
       (82, 'Jack', 'Clark', 'M', 31, 'Musicien avec un violon', 'Jouait de la musique dans le hall avec Nicholas'),
       (83, 'Eva', 'Turner', 'F', 36, 'Avocate avec des lunettes et une blouse',
        'Conseillait Elizabeth dans son bureau'),
       (84, 'Brian', 'Lewis', 'M', 29, 'Photographe avec un béret', 'Prenait des photos avec Dylan'),
       (85, 'Sophie', 'Foster', 'F', 33, 'Serrurière habillé toute en noir',
        'Changeait la serrure de la salle de bain'),
       (86, 'Mark', 'Morgan', 'M', 39, 'Traducteur avec des vêtements déchirés',
        'Était chez lui après avoir raté le bus'),
       (87, 'Lucy', 'Bennett', 'F', 41, 'Vétérinaire avec une blouse noire', 'Soignait les animaux avec Lilliane'),
       (88, 'David', 'Cook', 'M', 34, 'Homme de ménage en débardeur blanc', 'Nettoyait le 2ème étage du manoir'),
       (89, 'Emily', 'Bennett', 'F', 29, 'Styliste avec des cheveux bleus', 'Créait des tenues avec Fiona'),
       (90, 'Tony', 'Gray', 'M', 43, 'Fils de Vincent habillé en jean bleu', 'Observait les étoiles avec son père'),
       (91, 'Megan', 'Hughes', 'F', 24, 'Étudiante avec un sac à dos rouge', 'Étudiait avec Mia'),
       (92, 'Jeremy', 'Turner', 'M', 37, 'Électricien en tenue de travail bleu',
        'S''occupait des ampoules au sous-sol'),
       (93, 'Sarah', 'cliff', 'F', 31, 'Compositrice aux cheveux long et bouclés', 'Composait pour Laura'),
       (94, 'Alex', 'Brown', 'M', 46, 'Policier en tenue de travail', 'Faisait un contrôle de routine du manoir'),
       (95, 'Hannah', 'Bennett', 'F', 26, 'Forgeronne avec une visière de protection',
        'Forgeait des outils pour la famille'),
       (96, 'Kevin', 'Turner', 'M', 44, 'Agent de sécurité avec une oreillette habillé en costard noir',
        'Surveillait le sous-sol'),
       (97, 'Maria', 'Clark', 'F', 39, 'Pharmacienne habillée en blouse blanche',
        'Approvisionnait la pharmacie du manoir en médicaments'),
       (98, 'Alan', 'Reed', 'M', 32, 'Botaniste habillée en salopette marron',
        'Étudiait les plantes du jardin avec sa stagiaire'),
       (99, 'Hannah', 'Hinton', 'F', 22, 'Danseuse avec des chaussons de ballet', 'Répétait dans le groupe de Nina'),
       (100, 'Thiago', 'Peters', 'M', 38, 'Préparateur physique de William musclé et habillé en débardeur jaune',
        'Était chez lui'),
       (101, 'Dylan', 'Bray', 'M', 37, 'Ingénieur avec une lampe de poche', 'Réparait avec Robert'),
       (102, 'Casey', 'Lang', 'F', 31, 'Serveuse des repas de la famille au cheveux bruns et aux yeux marrons',
        'Était chez elle, en vacances'),
       (103, 'Jett', 'Finley', 'M', 46, 'Comédien avec un déguisement de clown',
        'Répétait la pièce avec ses collègues'),
       (104, 'Amaya', 'Jimenez', 'F', 27, 'Boulangère au tablier blanc et aux cheveux roux',
        'Est restée dans son atelier toute la journée'),
       (105, 'Alijah', 'Frank', 'M', 42, 'Agent de sécurité avec une oreillette habillé en noir',
        'Surveillait les entrées-sorties du manoir'),
       (106, 'Phoenix', 'Hopper', 'F', 39, 'Serveuse des repas de la famille habillé en pantalon noir et veste noir ',
        'Servait les repas durant la journée'),
       (107, 'Garnet', 'Wit', 'M', 32, 'Développeur informatique avec des lunettes et un pull rouge',
        'Créait un langage de programmation pour la famille'),
       (108, 'Daleyza', 'Morse', 'F', 29, 'Danseuse avec des chaussons de ballet',
        'Répétait dans le groupe de Nina et Hannah'),
       (109, 'Matthias', 'Graves', 'M', 25, 'Agent de sécurité très grand habillé en blanc',
        'Surveillait le premier étage'),
       (110, 'Kennedi', 'Whitehead', 'F', 34, 'Femme de ménage habillé en noir et blanc',
        'Nettoyait les vitres du premier étage'),
       (111, 'Nikolai', 'Berger', 'M', 41, 'Couturier avec un t-shirt à points',
        'Confectionnait la nouvelle robe d''Elizabeth'),
       (112, 'Ruth', 'Long', 'F', 30, 'Fleuriste avec des vêtements trempés',
        'S''occupait de cueillir les fleurs des jardins'),
       (113, 'Cullen', 'Woods', 'M', 28, 'Bûcheron à la chemise rouge et noire', 'Coupait les arbres avec sa hache'),
       (114, 'Blakely', 'Simon', 'F', 23, 'Femme de ménage habillé en t-shirt rouge',
        'Nettoyait les couloirs du 2ème étage'),
       (115, 'Andres', 'Sheppard', 'M', 42, 'Valet de chambre habillé en blanc',
        'Préparait les chambres pour la famille'),
       (116, 'Thea', 'Murphy', 'F', 29, 'Alchimiste vêtu d''une blouse blanche', 'Transformait la boue en or'),
       (117, 'Christopher', 'Gregory', 'M', 34, 'Écuyer Grand avec les cheveux bouclés',
        'Accompagnait Richard dans la discussion de propriétés avec Mark'),
       (118, 'Alice', 'Dixon', 'F', 30, 'Coiffeuse avec les cheveux long et blonds',
        'Organisait son nouveau salon de coiffure au sein du manoir'),
       (119, 'Miles', 'Harding', 'M', 39, 'Technicien en informatique avec un pantalon de jean noir',
        'Réparait avec Walter'),
       (120, 'Kaitlyn', 'Colon', 'F', 30, 'Diamantaire vêtue de bijoux',
        'Polissait les diamants pour la joaillerie du manoir'),
       (121, 'Stephen', 'Cass', 'M', 34, 'Organisateur d''évènement en costard bleu',
        'Prévoyait l''anniversaire de Richard'),
       (122, 'Vily', 'Bith', 'F', 29, 'Femme de pied aux chaussures roses', 'Acceuiellait le personnel et la famille '),
       (123, 'Oakley', 'Wright', 'M', 43, 'Physicien en blouse blanche',
        'Cherchait des nouvelles équations à résoudre'),
       (124, 'Elena', 'Pith', 'F', 24, 'Étudiante très grande et blonde', 'Étudiait avec Mia et Megan'),
       (125, 'Miaggi', 'Bax', 'M', 37, 'Humoriste au grand nez', 'Cherchait un invité pour le spectacle du lundi'),
       (126, 'Jessie', 'Mccarty', 'F', 31, 'Serveuse en tenue de travail blanche', 'Servait les boissons à la famille'),
       (127, 'Chance', 'Torres', 'M', 42, 'Comédien avec un costume de majordome', 'Répétait avec Jett'),
       (128, 'Katherine', 'Hutchinson', 'F', 26, 'Dresseuse de chiens aux cheveux courts et avec des lunettes',
        'Était occupée avec les chiens du manoir'),
       (129, 'Gregory', 'Hancock', 'M', 38, 'Documentariste avec un pantalon marron et une ceinture blanche',
        'Tournait un reportage sur la famille Thornton'),
       (130, 'Isabel', 'Bailor', 'F', 39, 'Jardinière avec une salopette rouge', 'Tondait le gazon d''un des jardins'),
       (131, 'Parker', 'Houston', 'M', 32, 'Cocher en costard violet', 'Déplaçait les voitures de la famille'),
       (132, 'Evelyn', 'Reyes', 'F', 41, 'Danseuse avec des chaussons de ballet',
        'Répétait avec Nina,Hannah et Daleyza'),
       (133, 'Brayden', 'Haley', 'M', 36, 'Maître de chais habillé en tenue décontractée',
        'Était dans la cave à vin toute la journée'),
       (134, 'Winter', 'Becker', 'F', 34, 'Peintre avec une salopette couleur bordeaux',
        'Peignait un autoportrait d''Elizabeth dans le salon'),
       (135, 'Abraham', 'Armstrong', 'M', 31, 'Sommelier habillé en noir',
        'Choisissait le meilleur vin de chez Brayden'),
       (136, 'Everly', 'Chavez', 'F', 25, 'Jardinière en veste bleu',
        'S''occupait d''un autre jardin que celui d''Isabel '),
       (137, 'Edgar', 'Bullock', 'M', 28, 'Magicien avec un haut-de-forme noir', 'Amusait la famille avec de la magie'),
       (138, 'Sage', 'Mccoy', 'F', 38, 'Philosophe vêtu d''un manteau noir', 'Cherchait la quête du sens de la vie'),
       (139, 'Emilio', 'Hart', 'M', 32, 'Palefrenier avec des vêtements plein de boue',
        'Était avec les chevaux toute la journée'),
       (140, 'Presley', 'Shepard', 'F', 28, 'Poète petite au yeux bleus',
        'Était en train d''écrire un poème sur la richesse'),
       (141, 'Jared', 'Goodwin', 'M', 34, 'Chapelier vêtu d''un t-shirt vert',
        'Concevait un nouveau haut-de-forme pour Edgar'),
       (142, 'Celeste', 'Walker', 'F', 31, 'Kinésithérapeute vêtu d''une blouse blanche',
        'Organisait ses prochains rendez-vous avec les membres de la famille'),
       (143, 'Braylen', 'Sampson', 'M', 39, 'Lustrier Grand et avec des chaussures rouges',
        'Entretenait les meubles du premier étage'),
       (144, 'Madelynn', 'Stafford', 'F', 25, 'Luthière vêtue d''une longue robe noire',
        'Réparait le piano d''Elizabeth'),
       (145, 'Sash', 'Salender', 'M', 34, 'Sculteur au yeux bleus avec un tablier noir',
        'Concevait sa dernière statue d''Elizabeth'),
       (146, 'Nova', 'Copeland', 'F', 29, 'Bibliothécaire aux lunnettes bleues et la robe verte',
        'Nettoyait la bibliothèque de 8h à 19h30'),
       (147, 'Avery', 'Wolf', 'M', 43, 'Maîtresse verrière avec une tenue de travail grise',
        'Fabriquait des verres à tiges pleines pour la famille'),
       (148, 'Azlio', 'Kizak', 'M', 24, 'Masseur personnel de la famille grand aux cheveux bruns',
        'N''a pas travaillé aujourd''hui'),
       (149, 'Jim', 'Kujow', 'M', 37, 'Humoriste très mauvais en chemise blanche', 'Accompagnait Miaggi'),
       (150, 'Zoe', 'Mann', 'F', 31, 'Decoratrice d''interieur au tablier blanc et une couette',
        'Dessinait les plans pour réaménager le bureau de Richard'),
       (151, 'Oliver', 'Ward', 'M', 28, 'Caméraman en t-shirt noir', 'Cadrait le documentaire de Gregory '),
       (152, 'Eleanor', 'Clark', 'F', 33, 'Vétérinaire avec une blouse blanche',
        'Soignait les animaux de compagnie dans la salle des animaux'),
       (153, 'Patrick', 'Brown', 'M', 40, 'Danseur de salsa avec des chaussures de danse',
        'Répétait une chorégraphie dans le salon'),
       (154, 'Victoria', 'Turner', 'F', 35, 'Nutritionniste avec des brochures sur la santé',
        'Donnait des conseils nutritionnels dans la salle de sport'),
       (155, 'George', 'Harris', 'M', 32, 'Pianiste avec des longs doigts', 'Jouait du piano avec Leonard'),
       (156, 'Linda', 'Evans', 'F', 27, 'Astronome avec une passion pour l''astronomie',
        'Observait les étoiles sur la terrasse'),
       (157, 'Alex', 'Turner', 'M', 34, 'Barman avec une chemise élégante',
        'Préparait des cocktails dans la salle de réception'),
       (158, 'Sophie', 'Lewis', 'F', 29, 'Joggeuse avec des baskets roses', 'Faisait son jogging dans le jardin'),
       (159, 'Henry', 'Anderson', 'M', 36, 'Sniper en tenue de camouflage', 'Surveillait l''ensemble du complexe'),
       (160, 'Clara', 'Taylor', 'F', 31, 'Factrice habillée en jaune et noir', 'Livrait le courrier du jour'),
       (161, 'Marcus', 'Bennett', 'M', 42, 'Analyste financier doté d''un costard noir',
        'Analysait les revenus de la famille dans le bureau principal'),
       (162, 'Cynthia', 'Turner', 'F', 33, 'Ouvrière avec un gilet orange', 'Réparait la route du manoir'),
       (163, 'Jordan', 'Allen', 'M', 49, 'Informaticien avec un badge d''identification',
        'Vérifiait les systèmes informatiques dans le salon'),
       (164, 'Celeste', 'Dixon', 'F', 29, 'Prêtresse vêtu d''une robe de cérémonie',
        'S''occupait de la pièce religieuse du manoir'),
       (165, 'Lucas', 'Hughes', 'M', 34, 'Chanteur avec une voix envoûtante', 'Chantait avec Dominic'),
       (166, 'Karla', 'Valencia', 'F', 47, 'Météorologue', 'Prévoyait la méteo de la semaine dans son bureau'),
       (167, 'Nasir', 'Mccarty', 'M', 51, 'Ornithologue vêtue d''un manteau de plume',
        'Étudiait les différents oiseaux présents sur le domaine'),
       (168, 'Everleigh', 'Kemp', 'F', 40, 'Parfumeuse avec une écharpe rose en plume',
        'Créait des parfums dans son atelier'),
       (169, 'Laura', 'Fesh', 'F', 34, 'Musicienne de la famille, blonde aux yeux verts',
        'Jouait de la flute à bec jusqu''à 19h'),
       (170, 'Marley', 'Mercado', 'F', 29, 'Styliste à la forte corpulence', 'Supervisait Fiona pour sa tenue'),
       (171, 'Mason', 'Cantu', 'M', 43, 'Fossoyeur à la peau très pâle',
        'Préparait une tombe sous l''ordre de William'),
       (172, 'Pilos', 'Servas', 'F', 24, 'Médecin chercheur en chemise à carreaux bleus',
        'Est resté dans son bureau à travailler toute la journée'),
       (173, 'Remy', 'Frye', 'M', 37, 'Cuisinier à la toque noir et au tablier rouge', 'Préparait le repas du midi'),
       (174, 'Kendall', 'Bender', 'F', 31, 'Soigneuse animalière avec une veste en cuir',
        'S''occupait des animaux du manoir'),
       (175, 'Pedro', 'Cox', 'M', 46, 'Plombier en tenue de travail bleu', 'Réparait la tuyauterie du manoir'),
       (176, 'Ruth', 'Pugh', 'F', 19, 'Secrétaire de Richard Blonde aux yeux bleus',
        'Prévoyait les futurs rendez-vous de Richard dans son bureau'),
       (177, 'Winston', 'Navarro', 'M', 29, 'Primatologue en blouse blanche et lunettes de protection',
        'Est resté toute la journée dans son laboratoire'),
       (178, 'Lauren', 'Ayers', 'F', 39, 'Conseillère financière habillé en costard noir', 'Parlait avec George')
;

INSERT INTO place (id, place_name, place_description)
VALUES (1, 'Chambre de Margaret et Richard', ' Chambre principale richement décorée, associant confort et élégance'),
       (2, 'Grand salon', 'Vaste espace de réception orné de meubles raffinés et d''une atmosphère chaleureuse'),
       (3, 'Couloirs du rez-de-chaussée', 'Longs passages connectant les différentes pièces du rez-de-chaussée'),
       (4, 'Bureau d''affaires', 'Espace professionnel, équipé pour les affaires et les réunions'),
       (5, 'Jardin Est', 'Partie est du jardin, paysagée avec des fleurs colorées et des chemins sinueux'),
       (6, 'Jardin Ouest', 'Partie ouest du jardin, aménagée avec des arbres majestueux et des bancs'),
       (7, 'Jardin Nord', 'Zone nord du jardin, offrant une vue panoramique sur les environs'),
       (8, 'Jardin Sud', 'Section sud du jardin, calme et paisible, avec des fontaines et des sculptures'),
       (9, 'Cuisine', 'Cuisine bien équipée, lieu de préparation des repas délicieux'),
       (10, 'Chambre des invités N°1', 'Chambre d''invités élégante avec tout le confort nécessaire'),
       (11, 'Chambre des invités N°2', 'Deuxième chambre d''invités, décorée avec goût et accueillante'),
       (12, 'Chambre des invités N°3', 'Troisième chambre d''invités, offrant une atmosphère relaxante'),
       (13, 'Salle de soins', 'Espace dédié aux soins médicaux, équipé pour les premiers secours'),
       (14, 'Bureau principal', 'Bureau principal, centre névralgique des affaires familiales'),
       (15, 'Bibliothèque', 'Grande bibliothèque, remplie de livres anciens et modernes'),
       (16, 'Atelier de peinture', 'Espace créatif pour les amateurs d''art, équipé pour la peinture'),
       (17, 'Salle d''informatique', 'Salle équipée d''ordinateurs pour travaux informatiques'),
       (18, 'Salle de sport', 'Salle dédiée à l''exercice physique, équipée de matériel moderne'),
       (19, 'Salle d''études', 'Espace calme propice à la concentration et à l''apprentissage'),
       (20, 'Bureau d''Elizabeth', 'Bureau personnel d''Elizabeth, organisé et fonctionnel'),
       (21, 'Bureau de Richard', 'Bureau privé de Richard, aménagé selon ses préférences'),
       (22, 'Hall d''entrée', 'Grand hall accueillant les visiteurs avec élégance et style'),
       (23, 'Sanitaire N°1 du rez-de-chaussée', 'Première salle de bains au rez-de-chaussée, propre et moderne'),
       (24, 'Sanitaire N°2 du rez-de-chaussée',
        'Deuxième salle de bains au rez-de-chaussée, avec des installations de qualité'),
       (25, 'Sanitaire N°3 du rez-de-chaussée',
        'Troisième salle de bains au rez-de-chaussée, pratique et bien aménagée'),
       (26, 'Sanitaire N°1 du 1er étage', 'Première salle de bains au premier étage, offrant confort et intimité'),
       (27, 'Sanitaire N°2 du 1er étage', 'Deuxième salle de bains au premier étage, élégante et fonctionnelle'),
       (28, 'Sanitaire N°1 du 2ème étage', 'Première salle de bains au deuxième étage, avec une vue magnifique'),
       (29, 'Sanitaire N°2 du 2ème étage', 'Deuxième salle de bains au deuxième étage, lumineuse et spacieuse'),
       (30, 'Sanitaire N°3 du 2ème étage',
        'Troisième salle de bains au deuxième étage, avec des installations modernes'),
       (31, 'Salle de réception', 'Espace dédié aux événements spéciaux, élégamment décoré'),
       (32, 'Salle des animaux', 'Espace pour les animaux domestiques, équipé pour leur bien-être'),
       (33, 'Atelier fashion', 'Espace créatif pour la conception de vêtements et d''accessoires'),
       (34, 'Salle de maintenance au sous-sol', 'Zone de maintenance équipée pour l''entretien de la propriété'),
       (35, 'Salle des caméras', 'Salle de surveillance, centralisant les caméras de sécurité'),
       (36, 'Parking Est', 'Zone de stationnement à l''est de la propriété'),
       (37, 'Parking Nord', 'Zone de stationnement au nord de la propriété'),
       (38, 'La cour', 'Espace ouvert au centre de la propriété, aménagé avec des bancs et des jardins'),
       (39, 'Terrasse', 'Plateforme extérieure avec une vue panoramique, idéale pour se détendre'),
       (40, 'Bureau adminastratif', 'Bureau dédié aux tâches administratives, organisé et efficace'),
       (41, 'Salle de musique', 'Espace dédié à la pratique et à l''appréciation de la musique'),
       (42, 'Couloirs du 1er étage', 'Longs passages connectant les différentes pièces du premier étage'),
       (43, 'Couloirs du 2ème étage', 'Longs passages connectant les différentes pièces du deuxième étage'),
       (44, 'Salle de bain N°1 2ème étage', 'Première salle de bains au deuxième étage, moderne et élégante'),
       (45, 'Salle de bain N°2 2ème étage',
        'Deuxième salle de bains au deuxième étage, avec des installations de qualité'),
       (46, 'Salle de bain N°3 2ème étage', 'Troisième salle de bains au deuxième étage, offrant confort et style'),
       (47, 'Chambre d''Elizabeth', 'Chambre personnelle d''Elizabeth, décorée selon ses goûts'),
       (48, 'Chambre de William', 'Chambre personnelle de William, alliant confort et fonctionnalité'),
       (49, 'Bureau de Margaret', 'Bureau personnel de Margaret, aménagé avec soin'),
       (50, 'Bureau de William', 'Bureau personnel de William, organisé pour la productivité'),
       (51, 'Forge au sous-sol', 'Espace équipé pour la forge et le travail du métal'),
       (52, 'Pharmacie du 1er étage', 'Espace médical pour le stockage de médicaments et fournitures'),
       (53, 'Laboratoire botanique', 'Espace dédié à l''étude des plantes et de la botanique'),
       (54, 'Théâtre du 1er étage', 'Salle de spectacle au premier étage, équipée pour les représentations'),
       (55, 'Escalier rez-de-chaussée -> 1er étage N°1', 'Premier escalier menant du rez-de-chaussée au premier étage'),
       (56, 'Escalier rez-de-chaussée -> 1er étage N°2',
        'Deuxième escalier reliant le rez-de-chaussée au premier étage'),
       (57, '1er étage -> 2ème étage N°1', 'Premier escalier reliant le premier étage au deuxième étage'),
       (58, '1er étage -> 2ème étage N°2', 'Deuxième escalier reliant le premier étage au deuxième étage'),
       (59, 'Ascenseur', 'Ascenseur, assurant un accès facile à tous les étages'),
       (60, 'Boulangerie', 'Espace dédié à la préparation du pain et des pâtisseries'),
       (61, 'Forêt privée', 'Forêt appartenant à la propriété, offrant un cadre naturel préservé'),
       (62, 'Laboratoire de chimie', 'Espace équipé pour des expériences chimiques et scientifiques'),
       (63, 'Salon de coiffure', 'Espace dédié aux soins capillaires, élégamment aménagé'),
       (64, 'Laboratoire de Physique', 'Espace équipé pour des expériences physiques et scientifiques'),
       (65, 'Cave à vin du sous-sol', 'Cave à vin bien garnie, stockant des millésimes précieux'),
       (66, 'Bureau de philosophie', 'Espace de réflexion et de travail pour les questions philosophiques'),
       (67, 'Secrétariat', 'Bureau administratif gérant les affaires courantes de la propriété'),
       (68, 'Atelier de sculture', 'Espace créatif pour la sculpture et les œuvres artistiques'),
       (69, 'Salon de massage', 'Espace dédié à la détente et aux soins du corps, avec une ambiance apaisante'),
       (70, 'Atelier de verre', 'Espace équipé pour la création artistique avec du verre'),
       (71, 'Salle de danse', 'Salle dédiée à la danse, avec un plancher adapté et des miroirs'),
       (72, 'Toit', 'Le sommet du bâtiment, offrant une vue panoramique sur les environs'),
       (73, 'Escalier 2ème étage -> Toit', 'Escalier menant du deuxième étage au toit'),
       (74, 'Pièce sainte', 'Espace dédié à des pratiques spirituelles, empreint de sérénité'),
       (75, 'Atelier de parfumerie', 'Espace créatif pour la conception de parfums et d''arômes'),
       (76, 'Cimetière', 'Zone dédiée à l''inhumation, entourée de verdure et de monuments funéraires'),
       (77, 'Cabinet médical', 'Espace médical pour les consultations et les soins de santé'),
       (78, 'Laboratoire de primatologie', 'Espace dédié à l''étude des primates et de la primatologie'),
       (79, 'Thermes Extérieurs', 'Espace en plein air équipé de bassins d''eau chaude pour la détente');



INSERT INTO object (id, object_name, object_description)
VALUES (1, 'Tableau ancien', 'Un tableau antique accroché au mur, représentant une scène mystérieuse.'),
       (2, 'Lampe en cristal', 'Une élégante lampe en cristal qui éclaire le salon principal.'),
       (3, 'Carnet secret', 'Un carnet mystérieux renfermant des notes énigmatiques.'),
       (4, 'Collier en argent', 'Un collier précieux abandonné sur la table du bureau.'),
       (5, 'Montre de poche', 'Une vieille montre de poche oubliée sur la cheminée.'),
       (6, 'Dague ancienne', 'Une dague ancienne exposée dans la salle de réception.'),
       (7, 'Journal intime', 'Un journal intime caché dans un tiroir du bureau principal.'),
       (8, 'Statuette en porcelaine', 'Une statuette délicate ornant une étagère de la bibliothèque.'),
       (9, 'Bouteille de vin', 'Une bouteille de vin rare provenant de la cave à vin du manoir de Richard.'),
       (10, 'Boîte à musique antique', 'Une boîte à musique ancienne trouvée dans la chambre d''Elizabeth.'),
       (11, 'Bouteille de Tubocurarine', 'Une bouteille suspecte contenant du Tubocurarine, un poison puissant.')
;



INSERT INTO position (object_place, object_concerned, hour)
VALUES (2, 1, '15:30:00'),
       (4, 2, '16:45:00'),
       (7, 3, '14:20:00'),
       (12, 4, '18:00:00'),
       (22, 5, '17:15:00'),
       (29, 6, '19:30:00'),
       (15, 7, '20:10:00'),
       (18, 8, '21:45:00'),
       (21, 9, '23:00:00'),
       (41, 10, '22:30:00'),
       (64, 11, '16:30:00'),
       (6, 11, '23:54:00');



INSERT INTO `phone_call` (`id`, `suspect_caller`, `suspect_called`, `hour`, `discussion`)
VALUES (1, 28, 31, '20:15:00',
        'Appel entre Grace Ward et Timothy Cook :\nGrace: Salut Timothy, c''est Grace. J''espère ne pas te déranger pendant les préparatifs du dîner.\nTimothy: Salut Grace, non aucun souci. Tout est sous contrôle ici. De quoi as-tu besoin?\nGrace: C''est à propos de l''anniversaire de Richard dans deux semaines. J''aimerais que tu sois le chef cuisinier pour l''événement. Tu penses que ce serait possible?\nTimothy: Ah, l''anniversaire de Richard, c''est vrai. Je serais honoré de m''occuper du repas. Qu''est-ce que tu avais en tête?\nGrace: Parfait! Je pensais à quelque chose de spécial, un menu qui impressionnera tout le monde. Des idées?\nTimothy: Absolument. On pourrait faire un menu personnalisé, avec des plats raffinés. Je vais préparer quelques suggestions pour que tu puisses choisir.\nGrace: Génial, Timothy! Richard adore la cuisine inventive. Je sais qu''il sera ravi. Et, entre nous, ça me permettra de m''assurer que tu es disponible ce soir-là. (Riant) Aucun problème, Grace. Je bloquerai la date dans mon agenda. Ça promet d''être une soirée mémorable. Merci beaucoup, Timothy. J''apprécie vraiment. On se voit ce soir pour le dîner. À ce soir, Grace. J''ai hâte.\n'),
       (2, 137, 141, '20:45:00',
        'Edgar Bullock: Allo, Jared? C''est Edgar. J''ai entendu dire que tu travaillais sur un nouveau haut-de-forme pour moi.\n\nJared Goodwin: Salut Edgar! Oui, c''est vrai. Je pense que tu vas adorer le design. Ça ajoute une touche de magie, tu sais, pour correspondre à ton numéro de magie.\n\nEdgar Bullock: Super, ça me plaît déjà. Mais, dis-moi, où étais-tu hier soir vers 21 heures? Il y a eu cette étrange affaire dans le quartier.\n\nJared Goodwin: Oh, moi? J''étais dans mon atelier toute la soirée, en train de peaufiner les détails du haut-de-forme. Tu sais bien que je suis perfectionniste.\n\nEdgar Bullock: C''est vrai. J''espère juste que personne n''a utilisé de tours de magie douteux pour détourner l''attention pendant que quelque chose se passait.\n\nJared Goodwin: Tu parles de magie, Edgar, mais tu sais que ce n''est qu''un divertissement. Quoi qu''''il en soit, tu étais où hier soir?\n\nEdgar Bullock: J''étais à la maison avec ma famille, à faire quelques tours pour les divertir. Rien de particulier.\n\nJared Goodwin: Bien, je suppose que nous sommes tous les deux des suspects potentiels alors. Mais entre magiciens et chapeliers, qui pourrait bien être derrière tout ça?\n\nEdgar Bullock: Mystère, mon ami. Mystère. Bon, je dois te laisser, mais tiens-moi au courant si tu entends quelque chose d''étrange.\n\nJared Goodwin: Pas de problème. À bientôt, Edgar'),
       (3, 130, 178, '14:30:00', 'Isabel Bailor: Salut Lauren, c''est Isabel. Comment ça va?\n
Lauren Ayers: Salut Isabel. Ça va bien, merci. J''espère que tu passes une bonne journée dans les jardins.\n
Isabel Bailor: Oui, ça va. On a eu une journée ensoleillée. Au fait, as-tu entendu parler d''événements étranges dans le quartier hier soir?\n
Lauren Ayers: Non, je n''ai rien entendu. Qu''est-ce qui s''est passé?\n
Isabel Bailor: Il y a des rumeurs, mais tu sais comment ça va. On ne sait jamais ce qui est vraiment arrivé.\n
Lauren Ayers: C''est vrai. Les rumeurs peuvent être trompeuses. J''étais chez moi hier soir. Rien d''excitant.\n
Isabel Bailor: Pareil ici. On ne devrait pas accorder trop d''importance à ces rumeurs.\n
Lauren Ayers: Absolument. Passons à des sujets plus légers. Tu as prévu quelque chose de spécial dans les jardins?\n
Isabel Bailor: Pas vraiment, juste l''entretien habituel. Et toi, des projets pour la soirée?\n
Lauren Ayers: Rien de particulier. Peut-être un bon livre. On se voit bientôt, Isabel.\n'),
       (4, 4, 110, '9:15:00', 'Emily Navy: Salut Kennedi. Comment ça va aujourd''hui ?\n
Kennedi Whitehead: Salut Emily. Les "fleurs" ont besoin d''un peu plus de "nourriture", tu ne trouves pas ?\n
Emily Navy: Les "tiges" sont un peu "sèches" en effet.\n
Kennedi Whitehead: En parlant de ça, j''ai remarqué que certaines "plantes" semblent un peu "fanées" ces jours-ci.\n
Emily Navy: Oui, elles ont peut-être besoin d''un peu de "soleil".\n
Kennedi Whitehead: J''ai entendu dire que le "jardin" pourrait bénéficier d''une touche spéciale de "poison".\n
Emily Navy: Hmm, peut-être une "solution" pourrait aider à "revitaliser" l''environnement.\n
Kennedi Whitehead: Qu''en dis-tu de "cultiver" certaines "herbes" pour que l''"effet" soit plus "intense" ?\n
Emily Navy: On pourrait envisager de "mélanger" quelques "ingrédients" spéciaux.\n
Kennedi Whitehead: Et peut-être que certaines "fleurs" pourraient être "arrosées" avec un peu de "substance spéciale".\n
Emily Navy: Oui, ça pourrait "élever" leur "parfum".\n
Kennedi Whitehead: Tu vois, Emily, il y a toujours un moyen de rendre notre travail plus intéressant. Que penses-tu de cette "idée" ?\n
Emily Navy: Il est toujours bon d''"explorer" de nouvelles "perspectives".\n'),
       (5, 4, 110, '18:56:34', 'Emily Navy: Salut Kennedi. Comment ça va en cette fin de journée ?\n
Kennedi Whitehead: Salut Emily. Les "ombres" semblent plus longues, n''est-ce pas ?\n
Emily Navy: ...\n
Kennedi Whitehead: J''ai pensé à ajouter un peu de "mystère" à notre routine de nettoyage.\n
Emily Navy: ...\n
Kennedi Whitehead: Imagine, Emily, si les "fenêtres" révélaient des "secrets" en fin de journée.\n
Emily Navy: ...\n
Kennedi Whitehead: Peut-être que le "manoir" a des histoires à raconter quand la "nuit" tombe.\n
Emily Navy: ...\n
Kennedi Whitehead: Qu''en dis-tu d''un peu de "poésie" dans notre travail quotidien ?\n
Emily Navy: ...\n
Kennedi Whitehead: Emily, parfois, il suffit d''un "soupçon" de "mystère" pour rendre la vie plus intéressante.\n
Emily Navy: ...\n
')
;


INSERT INTO `victim` (`id`, `name`, `cause_death`, `date_death`, `death_place`)
VALUES (1, 'Seraphina Thornton', 'Mort naturelle', '1695-06-11 07:15:00', 1),
       (2, 'Edmund Thornton', 'Maladie inconnue', '1750-03-10 10:15:00', 1),
       (3, 'Victoria Thornton', 'Accident de chasse', '1802-07-18 14:30:00', 61),
       (4, 'Reginald Thornton', 'Chute de cheval', '1825-11-05 16:45:00', 6),
       (5, 'Eleanor Thornton', 'Fièvre typhoïde', '1840-02-20 09:20:00', 13),
       (6, 'Alastair Thornton', 'Noyade accidentelle', '1868-06-30 11:10:00', 79),
       (7, 'Genevieve Thornton', 'Empoisonnement accidentel', '1885-09-12 13:55:00', 60),
       (8, 'Archibald Thornton', 'Mort au combat', '1708-04-03 18:40:00', 18),
       (9, 'Adelaide Thornton', 'Suicide', '1755-12-22 20:25:00', 72),
       (10, 'Winston Thornton', 'Accident domestique', '1798-08-17 22:05:00', 62),
       (11, 'Ophelia Thornton', 'Inconnue', '1833-04-08 01:30:00', 57),
       (12, 'Leopold Thornton', 'Foudroyé', '1877-10-25 03:20:00', 72),
       (13, 'Richard Thornton', 'Empoisonné', '2023-11-26 23:57:36', 21),
       (14, 'Cornelius Thornton', 'Accident de carrosse', '1720-09-28 09:50:00', 36),
       (15, 'Matilda Thornton', 'Chute d''escalier', '1766-01-14 11:45:00', 73),
       (16, 'Percival Thornton', 'Brûlé vif', '1809-05-02 13:35:00', 51),
       (17, 'Octavia Thornton', 'Attaqué par un ours', '1847-11-19 15:25:00', 32),
       (18, 'Mortimer Thornton', 'Assassinat', '1889-03-07 17:10:00', 39);



INSERT INTO `security_video` (recording_id, seen_suspect, recorded_place, hour)
VALUES (1, 4, 21, '19:15:27'),
       (2, 4, 23, '14:56:54'),
       (3, 4, 22, '12:30:00'),
       (4, 1, 1, '07:10:00'),
       (5, 95, 51, '09:30:00'),
       (6, 1, 1, '20:20:00'),
       (7, 7, 7, '07:07:07'),
       (8, 39, 35, '14:20:10'),
       (9, 149, 54, '20:00:00'),
       (10, 35, 34, '13:15:15');


INSERT INTO `witness` (`id`, `name`, `testimony`, `testimonal_date`, `accused_suspect`)
VALUES (1, 'Ariel Mooney', 'J''ai vu Emily Navy rôder près du bureau de la victime peu avant le meurtre.',
        '2023-11-27 12:00:00', 4),
       (2, 'Skyler Petersen', 'A mentionné qu''il avait vu William Thornton entrer dans le bureau de son père.',
        '2023-11-27 12:30:00', 3),
       (3, 'Riley Neal', 'A entendu Margaret Thornton discuter vivement avec la victime.', '2023-11-27 13:00:00', 1),
       (4, 'Shiloh Herring', 'A remarqué des comportements étranges de la part de Michael Brown cette nuit-là.',
        '2023-11-27 13:30:00', 9),
       (5, 'Oakley Richmond', 'A rapporté avoir vu John Smith près de la chambre de la victime.', '2023-11-27 14:00:00',
        5),
       (6, 'Rory Mayer', 'A déclaré avoir entendu des bruits suspects venant du bureau principal.',
        '2023-11-27 14:30:00', 14),
       (7, 'Phoenix Phelps', 'A mentionné avoir vu Rebecca Johnson revenir de sa course en ville couverte de sang.',
        '2023-11-27 15:00:00', 6),
       (8, 'Peyton Schneider', 'A signalé des signes de blessures sur le corps de la victime avant le meurtre.',
        '2023-11-27 15:30:00', 12),
       (9, 'Briar Roth', 'A accusé William Thornton de comportement agressif envers son père.', '2023-11-27 16:00:00',
        3),
       (10, 'Jaime Mcmillan', 'A vue Margaret quittant le bureau de la victime peu de temps avant le meurtre.',
        '2023-11-27 16:30:00', 1);


INSERT INTO `footprint` (`id`, `footprint_type`, `suspect_footprint`, `object_concerned`)
VALUES (1, 'Digitale', 4, 11),
       (2, 'Digitale', 121, 5),
       (3, 'Digitale', 122, 8),
       (4, 'Digitale', 123, 7),
       (5, 'Digitale', 124, 10),
       (6, 'Digitale', 125, 1),
       (7, 'Digitale', 126, 2),
       (8, 'Digitale', 127, 6),
       (9, 'Digitale', 128, 9),
       (10, 'Digitale', 129, 3);